旅遊景點api實測
wanwan1026/taipei-day-trip-website pull request #2
Opened 2021-04-24 12:49 UTC by wanwan1026

曾怡瑄
http://18.182.175.66:3000//api/attractions?page=1

http://18.182.175.66:3000/api/attractions?page=0&keyword=藝術

http://18.182.175.66:3000/api/attraction/100

2021-04-24 16:46 UTC, cwpeng requested changes
我測試了：
http://18.182.175.66:3000/api/attractions?page=0&keyword=臺北
會產生錯誤哦。

另外如果已經到了最後一頁，我們的 nextPage 要回應 null，意思是以下這個第 25 頁是你的最後一頁，那回應中的 nextPage 應該是 null。
http://18.182.175.66:3000/api/attractions?page=25

2021-04-25 01:51 UTC, wanwan1026 commented
老師 我改好了~
另外 我的最後一頁是第26頁~

2021-04-25 06:19 UTC, cwpeng approved these changes
OK. Good Fix.

2021-04-25 06:21 UTC, merged

2021-04-25 06:23 UTC, wanwan1026 commented
耶 : )