Develop
wanwan1026/taipei-day-trip-website pull request #5
Opened 2021-05-14 14:32 UTC by wanwan1026

曾怡瑄
完成這禮拜要求~請老師查看~~~

http://18.182.175.66:3000/
http://18.182.175.66:3000/attraction/8

2021-05-14 16:54 UTC, cwpeng requested changes
以下兩件事情請修正哦：
1. 註冊的視窗在小螢幕的時候會跑掉，我看了你的 CSS，或許你可以找到更明確的置中處理方式，而不是不斷的微調位置。
2. 密碼請使用密碼輸入框，不要明碼顯示。

2021-05-14 21:36 UTC, wanwan1026 commented
老師~ 我修改過了~ 老師再查看一下~~

2021-05-15 15:42 UTC, cwpeng approved these changes
好哦，這樣就可以了 ~~

2021-05-15 16:06 UTC, wanwan1026 commented
好~~ 耶~

2021-05-15 16:07 UTC, merged