預定系統
wanwan1026/taipei-day-trip-website pull request #6
Opened 2021-05-19 20:51 UTC by wanwan1026

曾怡瑄
完成這禮拜要求~ 請老師查看~~

http://18.182.175.66:3000/
http://18.182.175.66:3000/attraction/6
http://18.182.175.66:3000/booking

2021-05-20 09:11 UTC, cwpeng requested changes
細節請修改如下：
1. 登入視窗的按鈕，變得小小一個和設計不符。
2. 使用者未登入的狀況下進入 /booking，需要被強制導回首頁。
3. 使用者未登入的狀況下點擊景點頁面中的預定行程按鈕，需要跳出登入視窗。

2021-05-20 11:21 UTC, wanwan1026 commented
老師我修改完了~ 再請老師看一下~

2021-05-20 17:57 UTC, cwpeng requested changes
我一點進去就不會動了哦，景點頁面和預定行程頁面都是，注意一下新使用者的 Session 狀態，你可以用無痕視窗模擬第一次到訪的使用者，請參考以下截圖：
![未命名-2](https://user-images.githubusercontent.com/6104683/119026500-d229e400-b9d7-11eb-831e-21101d2f36b6.png)

2021-05-20 19:24 UTC, wanwan1026 commented
老師我修改完了~ 再請老師看一下~

2021-05-20 19:46 UTC, cwpeng commented
看起來有一樣的問題哦，開無痕視窗，或先移除所有 Cookies，然後試著直接點擊進入 http://18.182.175.66:3000/booking 看能不能看到和我一樣的錯誤。

2021-05-20 20:54 UTC, wanwan1026 commented
這次我用無痕試過了有成功跳轉~ 老師再檢查一下~~

2021-05-20 21:12 UTC, cwpeng requested changes
好哦，看起來是有好了，不過預定頁面的手機版面有點問題哦，請參考 375px 寬度的截圖如下：
1. 垃圾桶的位置和文字重疊。
2. 文字左邊會超出去。
3. 請盡可能仔細調整版面細節。

另外你的 POST /api/booking 的實作細節和要求的不同，雖然還是能夠運作，但建議你盡可能依照 API 文件的規格實作。像是傳遞資訊的欄位和格式，例如你其中一部份資訊是 cost:"新台幣 2500 元"，但我們要求的是 price:2500，這是一種總是能按照規格說明開發的習慣，未來和別人合作的時候會比較順利的。

![18 182 175 66_3000_booking](https://user-images.githubusercontent.com/6104683/119049295-f0510d80-b9f2-11eb-9845-901a02e4760f.png)

2021-05-21 04:20 UTC, wanwan1026 commented
老師~ 我改好了~ 老師再看一下
然後api的部分我下次會注意

2021-05-21 07:38 UTC, cwpeng approved these changes
好哦，這樣就可以了～

2021-05-21 12:29 UTC, wanwan1026 commented
好~~ : )

2021-05-24 08:45 UTC, merged