金流初步測試完成
wanwan1026/taipei-day-trip-website pull request #7
Opened 2021-05-27 09:43 UTC by wanwan1026

曾怡瑄
完成周作業~~ 老師查看一下~~

http://18.182.175.66:3000/

2021-05-27 14:18 UTC, cwpeng requested changes
結帳看起來是 OK 的，但是我被導到 /thankyou 的時候看不到訂單編號，請修正這點哦  ~

2021-05-27 15:05 UTC, wanwan1026 commented
老師~ 我改好了喔~ 在看一下~~

2021-05-27 20:50 UTC, cwpeng requested changes
現在想要預定行程的時候就會失敗了呦 ~

2021-05-27 21:12 UTC, wanwan1026 commented
老師～ 有什麼錯誤訊息嗎～ 因為我再試一次是沒問題的

2021-05-27 21:41 UTC, cwpeng commented
倒是沒有錯誤訊息，你可以看以下的測試紀錄影片，自己測試的時候可以開無痕視窗把自己當成第一次的使用者試試看。

https://user-images.githubusercontent.com/6104683/119900634-5a2f6100-bf77-11eb-96c4-33ff83eb0d3f.mp4

2021-05-27 23:00 UTC, wanwan1026 commented
這次試過，這樣無痕也可以正常顯示了~~

2021-05-27 23:21 UTC, cwpeng commented
我這邊點擊景點頁面中的預定行程按鈕，會完全跳過預定頁面的資訊，以及輸入信用卡的階段，直接被導向到 thankyou 頁面，這點還是一樣沒有變化，如果你那邊測試都正常，看要不要給我看一下你的測試畫面 ~

2021-05-27 23:24 UTC, wanwan1026 commented
如果已經有完成訂購行程的話，我的設定是會直接跳到感謝頁面(顯示的是已經完成的訂單)，一次只能預定一個行程，所以再次訂購別的行程的時候會跳到感謝頁面。 還是預期的是一個會員可以訂很多筆訂單嗎?

2021-05-27 23:26 UTC, cwpeng commented
一個會員可以有多筆訂單，站在電商的角度不可能會員想買第二次不讓他買吧 ~

2021-05-27 23:27 UTC, wanwan1026 commented
好~~ 那我知道要改甚麼了~~

2021-05-28 00:21 UTC, wanwan1026 commented
老師~~~ 我改好了~~~ 再再在看下XD

2021-05-28 20:26 UTC, cwpeng approved these changes
好哦，這樣就可以了，沒問題了 :)

2021-05-28 22:34 UTC, wanwan1026 commented
好～ 耶～

2021-05-28 22:35 UTC, merged